export const CUSTOMER_REGISTER = "CUSTOMER_REGISTER";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";

export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGIN_FAIL = "CUSTOMER_LOGIN_FAIL";

export const USER_AUTH = "USER_AUTH";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_ADDRESS = "GET_CUSTOMER_ADDRESS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUB_CATEGORIES_BY_CATEGORY = "GET_SUB_CATEGORIES_BY_CATEGORY";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_MORE_PRODUCTS_BY_CATEGORY = "GET_MORE_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_SUB_CATEGORY = "GET_PRODUCTS_BY_SUB_CATEGORY";

export const LOGOUT = "LOGOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const GET_USER_CART_ITEMS = "GET_USER_CART_ITEMS";
export const DECREASE_CART_PRODUCT_QUANTITY = "DECREASE_CART_PRODUCT_QUANTITY";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";

export const MAKE_ORDER = "MAKE_ORDER";
export const GET_ORDERS = "GET_ORDERS";

export const GET_LANGUAGE = "GET_LANGUAGE";
